// <auto-generated />
using System;
using Agenda.WebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Agenda.WebApi.Migrations
{
    [DbContext(typeof(AgendaContext))]
    [Migration("20210817142401_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Agenda.WebApi.Model.Contato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DataAniversario")
                        .HasColumnType("datetime2");

                    b.Property<string>("HomePage")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdTipoContato")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sobrenome")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<int?>("TipoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoId");

                    b.ToTable("Tbl_Contatos");
                });

            modelBuilder.Entity("Agenda.WebApi.Model.EmailContato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("ContatoId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("IdContato")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContatoId");

                    b.ToTable("Tbl_Emails_Contato");
                });

            modelBuilder.Entity("Agenda.WebApi.Model.Models_Endereco.Bairro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tbl_Bairros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Grã-Duquesa"
                        });
                });

            modelBuilder.Entity("Agenda.WebApi.Model.Models_Endereco.Cidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("EstadoId")
                        .HasColumnType("int");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.ToTable("Tbl_Cidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdEstado = 1,
                            Nome = "Governador Valadares"
                        });
                });

            modelBuilder.Entity("Agenda.WebApi.Model.Models_Endereco.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("BairroId")
                        .HasColumnType("int");

                    b.Property<int?>("CidadeId")
                        .HasColumnType("int");

                    b.Property<string>("Complemento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ContatoId")
                        .HasColumnType("int");

                    b.Property<int>("IdBairro")
                        .HasColumnType("int");

                    b.Property<int>("IdCidade")
                        .HasColumnType("int");

                    b.Property<int>("IdContato")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoEndereco")
                        .HasColumnType("int");

                    b.Property<string>("Logradouro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int?>("TipoEnderecoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BairroId");

                    b.HasIndex("CidadeId");

                    b.HasIndex("ContatoId");

                    b.HasIndex("TipoEnderecoId");

                    b.ToTable("Tbl_Enderecos_Contato");
                });

            modelBuilder.Entity("Agenda.WebApi.Model.Models_Endereco.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sigla")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tbl_Estados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Minas Gerais",
                            Sigla = "MG"
                        });
                });

            modelBuilder.Entity("Agenda.WebApi.Model.Models_Endereco.TipoEndereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descricao")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Tbl_Tipos_Endereco");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Casa"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Trabalho"
                        });
                });

            modelBuilder.Entity("Agenda.WebApi.Model.Telefone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("ContatoId")
                        .HasColumnType("int");

                    b.Property<int>("IdContato")
                        .HasColumnType("int");

                    b.Property<bool>("IsFax")
                        .HasColumnType("bit");

                    b.Property<string>("Numero")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.HasIndex("ContatoId");

                    b.ToTable("Tbl_Telefones_Contato");
                });

            modelBuilder.Entity("Agenda.WebApi.Model.TipoContato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descricao")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Tbl_Tipos_Contato");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "CLIENTE"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "OUTROS"
                        });
                });

            modelBuilder.Entity("Agenda.WebApi.Model.Contato", b =>
                {
                    b.HasOne("Agenda.WebApi.Model.TipoContato", "Tipo")
                        .WithMany()
                        .HasForeignKey("TipoId");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("Agenda.WebApi.Model.EmailContato", b =>
                {
                    b.HasOne("Agenda.WebApi.Model.Contato", "Contato")
                        .WithMany()
                        .HasForeignKey("ContatoId");

                    b.Navigation("Contato");
                });

            modelBuilder.Entity("Agenda.WebApi.Model.Models_Endereco.Cidade", b =>
                {
                    b.HasOne("Agenda.WebApi.Model.Models_Endereco.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId");

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("Agenda.WebApi.Model.Models_Endereco.Endereco", b =>
                {
                    b.HasOne("Agenda.WebApi.Model.Models_Endereco.Bairro", "Bairro")
                        .WithMany()
                        .HasForeignKey("BairroId");

                    b.HasOne("Agenda.WebApi.Model.Models_Endereco.Cidade", "Cidade")
                        .WithMany()
                        .HasForeignKey("CidadeId");

                    b.HasOne("Agenda.WebApi.Model.Contato", "Contato")
                        .WithMany()
                        .HasForeignKey("ContatoId");

                    b.HasOne("Agenda.WebApi.Model.Models_Endereco.TipoEndereco", "TipoEndereco")
                        .WithMany()
                        .HasForeignKey("TipoEnderecoId");

                    b.Navigation("Bairro");

                    b.Navigation("Cidade");

                    b.Navigation("Contato");

                    b.Navigation("TipoEndereco");
                });

            modelBuilder.Entity("Agenda.WebApi.Model.Telefone", b =>
                {
                    b.HasOne("Agenda.WebApi.Model.Contato", "Contato")
                        .WithMany()
                        .HasForeignKey("ContatoId");

                    b.Navigation("Contato");
                });
#pragma warning restore 612, 618
        }
    }
}
